export let workouts = [
  {
    name: "Bench Press",
    img: "Assets/bench_press.gif",
    bodyPart: ["Chest"],
    bodyweight: false,
    compound: true,
    equipment: "Bench and Barbell",
  },
  {
    name: "Incline Press",
    img: "Assets/incline_press.gif",
    bodyPart: ["Chest"],
    bodyweight: false,
    compound: false,
    equipment: "Bench and Barbell",
  },
  {
    name: "Shoulder Press",
    img: "Assets/shoulder_press.gif",
    bodyPart: ["Shoulders"],
    bodyweight: false,
    compound: true,
    equipment: "Dumbbells or Barbell",
  },
  {
    name: "Lateral Raises",
    img: "Assets/lateral_raises.gif",
    bodyPart: ["Shoulders"],
    bodyweight: false,
    compound: false,
    equipment: "Dumbbells or Cable Machine",
  },
  {
    name: "Skull Crushers",
    img: "Assets/skull_crushers.gif",
    bodyPart: ["Triceps"],
    bodyweight: false,
    compound: true,
    equipment: "E-Z Curl Bar or Dumbbells",
  },
  {
    name: "Tricep Rope Pushdown",
    img: "Assets/tricep_rope_pushdown.gif",
    bodyPart: ["Triceps"],
    bodyweight: false,
    compound: false,
    equipment: "Cable Machine",
  },
  {
    name: "Barbell Rows",
    img: "Assets/barbell_rows.gif",
    bodyPart: ["Back"],
    bodyweight: false,
    compound: true,
    equipment: "Barbell",
  },
  {
    name: "Lat Pull Down",
    img: "Assets/lat_pull_down.gif",
    bodyPart: ["Back"],
    bodyweight: false,
    compound: false,
    equipment: "Lat Pulldown Machine",
  },
  {
    name: "Shrugs",
    img: "Assets/shrugs.gif",
    bodyPart: ["Back"],
    bodyweight: false,
    compound: true,
    equipment: "Dumbell or Barbell",
  },
  {
    name: "Bicep Curl",
    img: "Assets/bicep_curls.gif",
    bodyPart: ["Biceps"],
    bodyweight: false,
    compound: true,
    equipment: "Dumbell or Barbell",
  },
  {
    name: "Hammer Curl",
    img: "Assets/hammer_curl.gif",
    bodyPart: ["Biceps"],
    bodyweight: false,
    compound: false,
    equipment: "Dumbell",
  },
  {
    name: "Weighted Squat",
    img: "Assets/weighted_squat.gif",
    bodyPart: ["Legs"],
    bodyweight: false,
    compound: true,
    equipment: "Barbell, Squat Rack",
  },
  {
    name: "Deadlift",
    img: "Assets/deadlift.gif",
    bodyPart: ["Back", "Legs"],
    bodyweight: false,
    compound: true,
    equipment: "Barbell, Weight Plates",
  },
  {
    name: "Leg Extension",
    img: "Assets/leg_extension.gif",
    bodyPart: ["Legs"],
    bodyweight: false,
    compound: false,
    equipment: "Leg Extension Machine",
  },
  {
    name: "Leg Curls",
    img: "Assets/leg_curls.gif",
    bodyPart: ["Legs"],
    bodyweight: false,
    compound: false,
    equipment: "Leg Curl Machine",
  },
  {
    name: "Crunches",
    img: "Assets/crunches.gif",
    bodyPart: ["Abs"],
    bodyweight: true,
    compound: false,
    equipment: "None",
  },
  {
    name: "Plank",
    img: "Assets/plank.gif",
    bodyPart: ["Abs"],
    bodyweight: true,
    compound: true,
    equipment: "None",
  },
  {
    name: "Lunges",
    img: "Assets/lunges.gif",
    bodyPart: ["Legs"],
    bodyweight: true,
    compound: true,
    equipment: "None",
  },
  {
    name: "Pistol Squat",
    img: "Assets/pistol_squat.gif",
    bodyPart: ["Legs"],
    bodyweight: true,
    compound: false,
    equipment: "None",
  },
  {
    name: "Push-ups",
    img: "Assets/push_ups.gif",
    bodyPart: ["Chest", "Shoulders", "Triceps"],
    bodyweight: true,
    compound: true,
    equipment: "None",
  },
  {
    name: "Dips",
    img: "Assets/dips.gif",
    bodyPart: ["Chest", "Shoulders", "Triceps"],
    bodyweight: true,
    compound: true,
    equipment: "Parallel Bars or Dip Station",
  },
  {
    name: "Pull-ups",
    img: "Assets/pull_ups.gif",
    bodyPart: ["Back", "Biceps"],
    bodyweight: true,
    compound: true,
    equipment: "Pull-up Bar",
  },
  {
    name: "Pike Push-ups",
    img: "Assets/pike_push_ups.gif",
    bodyPart: ["Chest", "Triceps", "Shoulders"],
    bodyweight: true,
    compound: true,
    equipment: "None",
  },
  {
    name: "Diamond Push-ups",
    img: "Assets/diamond_push_ups.gif",
    bodyPart: ["Chest", "Triceps"],
    bodyweight: true,
    compound: true,
    equipment: "None",
  },
];
